[package]
name = "net_profiler"
description = "A tool for managing different network adapter profiles, designed for ROV connections"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.28.1", features = ["persistence"] }
egui = "0.28.1"
egui-file-dialog = "0.6.0"
network-interface = "2.0.0"
serde = { version = "1.0.208", features = ["derive"] }
serde_json = "1.0.125"

[profile.dev]
debug = 0

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
